title:            Scribble
description:      A jekyll theme. Because I scribble.
url:              http://chloerei.com/scribble
baseurl:          /scribble
signoff:          Rei
disqus_shortname: chloerei
google_analytics_id: UA-2196462-7

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://chloerei.com
    external:     true
  - name:         Email
    url:          mailto:chloerei@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/chloerei/scribble
    external:     true

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
